# Form implementation generated from reading ui file 'ui\definition_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DefinitionDialog(object):
    def setupUi(self, DefinitionDialog):
        DefinitionDialog.setObjectName("DefinitionDialog")
        DefinitionDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DefinitionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(DefinitionDialog)
        self.buttonBox.accepted.connect(DefinitionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DefinitionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DefinitionDialog)

    def retranslateUi(self, DefinitionDialog):
        _translate = QtCore.QCoreApplication.translate
        DefinitionDialog.setWindowTitle(_translate("DefinitionDialog", "Dialog"))
