# Form implementation generated from reading ui file 'ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from importlib.resources import path
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        with path("ui", "DiagramDetective.ico") as f_path:
            icon.addPixmap(QtGui.QPixmap(str(f_path)), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuDefinition_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menuDefinition_2.setObjectName("menuDefinition_2")
        self.menuInvestigation = QtWidgets.QMenu(parent=self.menubar)
        self.menuInvestigation.setObjectName("menuInvestigation")
        self.menuStatement = QtWidgets.QMenu(parent=self.menubar)
        self.menuStatement.setObjectName("menuStatement")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewInvestigation = QtGui.QAction(parent=MainWindow)
        self.actionNewInvestigation.setObjectName("actionNewInvestigation")
        self.actionDefine = QtGui.QAction(parent=MainWindow)
        self.actionDefine.setObjectName("actionDefine")
        self.menuDefinition_2.addAction(self.actionDefine)
        self.menuInvestigation.addAction(self.actionNewInvestigation)
        self.menubar.addAction(self.menuInvestigation.menuAction())
        self.menubar.addAction(self.menuDefinition_2.menuAction())
        self.menubar.addAction(self.menuStatement.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diagram Detective"))
        self.menuDefinition_2.setTitle(_translate("MainWindow", "Definition"))
        self.menuInvestigation.setTitle(_translate("MainWindow", "Case"))
        self.menuStatement.setTitle(_translate("MainWindow", "Statement"))
        self.actionNewInvestigation.setText(_translate("MainWindow", "New"))
        self.actionDefine.setText(_translate("MainWindow", "Define..."))

